name = "hone-relay"
main = "src/index.js"
compatibility_date = "2024-12-01"

[durable_objects]
bindings = [
  { name = "RELAY", class_name = "HONERelay" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["HONERelay"]
