"use strict";

/**
 * HONE P2P Message Authentication
 * Shin Devlin
 *
 * Centralized cryptographic authentication for P2P messages.
 * Provides signing, verification, allowlists, and key-ownership proofs.
 *
 * Signatures are required by default. Unsigned messages are rejected unless
 * HONE_REQUIRE_SIGNATURES=false is set explicitly for local legacy/test use.
 */

const crypto = require("crypto");

// Signature enforcement only applies to value-moving operations (spend, stake,
// delegation, escrow). Mining, clock heartbeats, and block proposals do NOT
// require signatures — their security comes from VRF rotation and verification.
const REQUIRE_SIGNATURES = process.env.HONE_REQUIRE_SIGNATURES !== "false";

// Entry types that MUST be signed — these move value or delegate authority.
// All other operations (heartbeats, proposals, sensor readings) are unsigned.
const SIGNATURE_REQUIRED_TYPES = [
  "TRANSFER",
  "STAKE",
  "UNSTAKE",
  "DELEGATE",
  "UNDELEGATE",
  "ESCROW_LOCK",
  "ESCROW_RELEASE",
  "ESCROW_REFUND",
  "BRIDGE_WRAP",
  "BRIDGE_UNWRAP",
  "KEY_ROTATE",
];

function requiresSignature(entryType) {
  return SIGNATURE_REQUIRED_TYPES.indexOf(entryType) !== -1;
}

// ---------------------------------------------------------------------------
// Canonical data hashing
// ---------------------------------------------------------------------------

/**
 * Produce a deterministic SHA-256 hex digest of a message data payload.
 * Keys are sorted to guarantee the same hash regardless of insertion order.
 */
function hashMessageData(data) {
  var canonical = JSON.stringify(data, Object.keys(data).sort());
  return crypto.createHash("sha256").update(canonical).digest("hex");
}

// ---------------------------------------------------------------------------
// Sign / verify helpers (wrap keyManager, lazy-required to avoid circular deps)
// ---------------------------------------------------------------------------

/**
 * Sign a data payload using the node's private key.
 * @param {Object} data       — message data to sign (will be hashed)
 * @param {string} privateKey — hex-encoded secp256k1 private key
 * @returns {{ signature: string, recovery: number }}
 */
function signMessage(data, privateKey) {
  var hash = hashMessageData(data);
  var keyManager = require("../wallet/keyManager");
  return keyManager.signTransaction(hash, privateKey);
}

/**
 * Verify a message data payload against a signature and public key.
 * @param {Object} data      — original message data object
 * @param {string} signature — hex-encoded ECDSA signature
 * @param {string} publicKey — hex-encoded compressed secp256k1 public key
 * @returns {boolean}
 */
function verifyMessage(data, signature, publicKey) {
  var hash = hashMessageData(data);
  var keyManager = require("../wallet/keyManager");
  try {
    return keyManager.verifySignature(hash, signature, publicKey);
  } catch (_) {
    return false;
  }
}

/**
 * Verify a message data payload against an on-chain account's public key.
 * @param {string} username — HONE account name
 * @param {Object} data     — message data
 * @param {string} signature
 * @param {string} keyRole  — "owner" | "active" | "posting" | "memo" (default "active")
 * @returns {boolean}
 */
function verifyAccountSignature(username, data, signature, keyRole) {
  var stateStore = require("../chain/stateStore");
  var account = stateStore.getAccount(username);
  if (!account || !account.public_keys) return false;
  var pubKey = account.public_keys[keyRole || "active"];
  if (!pubKey) return false;
  return verifyMessage(data, signature, pubKey);
}

// ---------------------------------------------------------------------------
// Entry type allowlists
// ---------------------------------------------------------------------------

/**
 * Entry types that may be gossiped via MEMPOOL_ENTRY.
 * These are user-initiated actions that need propagation before block inclusion.
 */
const MEMPOOL_ALLOWED_TYPES = [
  "TRANSFER",
  "ACCOUNT_CREATE",
  "STAKE",
  "UNSTAKE",
  "ESCROW_LOCK",
  "ESCROW_RELEASE",
  "ESCROW_REFUND",
  "STORE_OPEN",
  "PRODUCT_CREATE",
  "ORDER_PLACE",
  "SERVICE_DEPLOY",
  "SERVICE_HEARTBEAT",
  "STORAGE_HEARTBEAT",
  "BLOB_STORE_COMMIT",
  "ORACLE_REPORT",
  "SENSOR_READING",
  "SNAPSHOT_COMMIT",
  "BRIDGE_WRAP",
  "BRIDGE_UNWRAP",
  "TOTP_POLICY",
  "KEY_ROTATE",
  "PROJECT_CREATE",
  "DELEGATE",
  "UNDELEGATE",
  "DEVICE_AUTHORIZE",
  "DEVICE_REVOKE",
  "TOOL_CAPABILITY_REGISTER",
  "TOOL_TRACE_COMMIT",
  "INFERENCE_CHARGE",
  // Shard inference (Mode B — pipeline)
  "SHARD_REGISTER",
  "SHARD_GROUP_FORM",
  "SHARD_ACTIVATE",
  "SHARD_RESULT",
  // Ensemble inference (Mode A — majority-vote)
  "ENSEMBLE_CLAIM",
  "ENSEMBLE_RESULT",
  "ENSEMBLE_CONSENSUS",
  // Scientific compute engine (v3.2)
  "SCIENTIFIC_JOB",
  "SCIENTIFIC_RESULT",
  "NODE_LATENCY",
];

/**
 * Entry types that are generated by chain authority — must only arrive inside
 * EPOCH_FINALIZED block payloads. Receiving one via MEMPOOL_ENTRY is an attack.
 */
const BLOCK_ONLY_TYPES = [
  "MINING_REWARD",
  "FAUCET",
  "CLOCK_REWARD",
  "STORAGE_REWARD",
  "SERVICE_REWARD",
  "IOT_REWARD",
  "FINALIZATION_CONSENSUS",
];

/**
 * Verify a proposal/block signature that was made by a device key.
 * Accepts either:
 *   (a) a device key that is registered on-chain as a delegate for proposer, OR
 *   (b) the proposer's own active key (backwards-compat, single-device mode).
 *
 * @param {string} proposer   — HONE account name (e.g. 'natoshisakamoto')
 * @param {string} deviceId   — hex device public key that signed (may equal proposer's active key)
 * @param {Object} data       — message data that was signed
 * @param {string} signature  — hex ECDSA signature
 * @returns {boolean}
 */
function verifyDeviceOrAccountSignature(proposer, deviceId, data, signature) {
  var stateStore = require('../chain/stateStore');

  // Path A: device key registered on-chain as a delegate
  if (deviceId) {
    var rec = stateStore.getDeviceOwner(deviceId);
    if (rec && rec.owner === proposer) {
      return verifyMessage(data, signature, deviceId);
    }
  }

  var account = stateStore.getAccount(proposer);
  if (!account || !account.public_keys) return false;

  // Path B: posting key — the correct key for mining operations (can't move funds).
  // Try this first so miners never need their spending key on a hot machine.
  var postingPub = account.public_keys.posting;
  if (postingPub) {
    if (!deviceId || deviceId === postingPub) {
      if (verifyMessage(data, signature, postingPub)) return true;
    }
  }

  // Path C: active key fallback — accepted for backwards compatibility but
  // miners should rotate to HONE_POSTING_KEY.
  var activePub = account.public_keys.active;
  if (!activePub) return false;
  if (deviceId && deviceId !== activePub) return false;
  return verifyMessage(data, signature, activePub);
}

module.exports = {
  REQUIRE_SIGNATURES,
  SIGNATURE_REQUIRED_TYPES,
  requiresSignature,
  hashMessageData,
  signMessage,
  verifyMessage,
  verifyAccountSignature,
  verifyDeviceOrAccountSignature,
  MEMPOOL_ALLOWED_TYPES,
  BLOCK_ONLY_TYPES,
};
