"use strict";

/**
 * BTCPC P2P Message Authentication
 * Shin Devlin
 *
 * Centralized cryptographic authentication for P2P messages.
 * Provides signing, verification, allowlists, and key-ownership proofs.
 *
 * Signatures required by default. Unsigned messages are rejected unless
 * BTCPC_REQUIRE_SIGNATURES=false is set (legacy/test mode only).
 */

const crypto = require("crypto");

// When true, reject any message that lacks a required signature.
// Default: false during genesis (nodes need time to set up signing keys).
// Set BTCPC_REQUIRE_SIGNATURES=true to enforce strict mode after key setup.
const REQUIRE_SIGNATURES = process.env.BTCPC_REQUIRE_SIGNATURES === "true";

// ---------------------------------------------------------------------------
// Canonical data hashing
// ---------------------------------------------------------------------------

/**
 * Produce a deterministic SHA-256 hex digest of a message data payload.
 * Keys are sorted to guarantee the same hash regardless of insertion order.
 */
function hashMessageData(data) {
  var canonical = JSON.stringify(data, Object.keys(data).sort());
  return crypto.createHash("sha256").update(canonical).digest("hex");
}

// ---------------------------------------------------------------------------
// Sign / verify helpers (wrap keyManager, lazy-required to avoid circular deps)
// ---------------------------------------------------------------------------

/**
 * Sign a data payload using the node's private key.
 * @param {Object} data       — message data to sign (will be hashed)
 * @param {string} privateKey — hex-encoded secp256k1 private key
 * @returns {{ signature: string, recovery: number }}
 */
function signMessage(data, privateKey) {
  var hash = hashMessageData(data);
  var keyManager = require("../wallet/keyManager");
  return keyManager.signTransaction(hash, privateKey);
}

/**
 * Verify a message data payload against a signature and public key.
 * @param {Object} data      — original message data object
 * @param {string} signature — hex-encoded ECDSA signature
 * @param {string} publicKey — hex-encoded compressed secp256k1 public key
 * @returns {boolean}
 */
function verifyMessage(data, signature, publicKey) {
  var hash = hashMessageData(data);
  var keyManager = require("../wallet/keyManager");
  try {
    return keyManager.verifySignature(hash, signature, publicKey);
  } catch (_) {
    return false;
  }
}

/**
 * Verify a message data payload against an on-chain account's public key.
 * @param {string} username — BTCPC account name
 * @param {Object} data     — message data
 * @param {string} signature
 * @param {string} keyRole  — "owner" | "active" | "posting" | "memo" (default "active")
 * @returns {boolean}
 */
function verifyAccountSignature(username, data, signature, keyRole) {
  var stateStore = require("../chain/stateStore");
  var account = stateStore.getAccount(username);
  if (!account || !account.public_keys) return false;
  var pubKey = account.public_keys[keyRole || "active"];
  if (!pubKey) return false;
  return verifyMessage(data, signature, pubKey);
}

// ---------------------------------------------------------------------------
// Entry type allowlists
// ---------------------------------------------------------------------------

/**
 * Entry types that may be gossiped via MEMPOOL_ENTRY.
 * These are user-initiated actions that need propagation before block inclusion.
 */
const MEMPOOL_ALLOWED_TYPES = [
  "TRANSFER",
  "ACCOUNT_CREATE",
  "STAKE",
  "UNSTAKE",
  "ESCROW_LOCK",
  "ESCROW_RELEASE",
  "ESCROW_REFUND",
  "STORE_OPEN",
  "PRODUCT_CREATE",
  "ORDER_PLACE",
  "SERVICE_DEPLOY",
  "SERVICE_HEARTBEAT",
  "STORAGE_HEARTBEAT",
  "BLOB_STORE_COMMIT",
  "ORACLE_REPORT",
  "SENSOR_READING",
  "SNAPSHOT_COMMIT",
  "BRIDGE_WRAP",
  "BRIDGE_UNWRAP",
];

/**
 * Entry types that are generated by chain authority — must only arrive inside
 * EPOCH_FINALIZED block payloads. Receiving one via MEMPOOL_ENTRY is an attack.
 */
const BLOCK_ONLY_TYPES = [
  "MINING_REWARD",
  "FAUCET",
  "CLOCK_REWARD",
  "STORAGE_REWARD",
  "SERVICE_REWARD",
  "IOT_REWARD",
];

module.exports = {
  REQUIRE_SIGNATURES,
  hashMessageData,
  signMessage,
  verifyMessage,
  verifyAccountSignature,
  MEMPOOL_ALLOWED_TYPES,
  BLOCK_ONLY_TYPES,
};
