//! Inference mining loop for the Android micronode.
//!
//! work_value = tokens generated by the local candle LLM.
//! compute_proof = SHA-256 hex of the inference output.
//!
//! No SHA-256 grinding. Running the model IS the proof of work.
//! Miners submit only a Mine entry; MineReward is emitted by clock nodes
//! after epoch seal quorum is reached.

use std::sync::Arc;
use std::time::Duration;
use sha2::{Digest, Sha256};
use tracing::{info, warn};

use btcpc_types::{LedgerEntry, EPOCH_MS};

use crate::chain::Chain;
use crate::llm::LlmEngine;
use crate::net::NetCmd;

pub async fn run_miner(
    chain:       Arc<Chain>,
    account:     String,
    genesis_ts:  u64,
    llm:         Arc<tokio::sync::Mutex<LlmEngine>>,
    cmd_tx:      tokio::sync::mpsc::Sender<NetCmd>,
    mut shutdown: tokio::sync::broadcast::Receiver<()>,
) {
    info!("miner: started, account={}", account);

    let now = now_ms();
    if genesis_ts > now {
        let wait = genesis_ts - now;
        info!("miner: waiting {}s for genesis", wait / 1000);
        tokio::time::sleep(Duration::from_millis(wait)).await;
    }

    let mut last_produced = chain.store.latest_epoch().unwrap_or(0);

    loop {
        let next_epoch = last_produced + 1;

        tokio::select! {
            _ = shutdown.recv() => break,
            _ = sleep_until_epoch(next_epoch, genesis_ts) => {}
        }

        // Run on-device inference — this is the proof of work.
        let (work_value, compute_proof) = {
            let mut engine = llm.lock().await;
            if engine.ensure_ready().await {
                let prompt = format!(
                    "btcpc epoch {} miner {}",
                    next_epoch, account,
                );
                match engine.generate(&prompt, 64).await {
                    Ok(output) => {
                        let tokens = output.split_whitespace().count() as u64;
                        let proof  = hex::encode(Sha256::digest(output.as_bytes()));
                        info!("miner: epoch {} — {} tokens", next_epoch, tokens);
                        (tokens, proof)
                    }
                    Err(e) => {
                        warn!("miner: inference failed epoch {}: {}", next_epoch, e);
                        (0, String::new())
                    }
                }
            } else {
                // Model still downloading — submit zero-work Mine entry this epoch.
                (0, String::new())
            }
        };

        // Build and apply Mine entry locally, then broadcast as gossip.
        let entry = LedgerEntry::Mine {
            miner:      account.clone(),
            epoch:      next_epoch,
            work_value,
            block_hash: compute_proof.clone(),
        };
        let _ = chain.apply_entry(&entry);

        let envelope = serde_json::json!({"entry": entry});
        if let Ok(data) = serde_json::to_vec(&envelope) {
            let _ = cmd_tx.send(NetCmd::Broadcast {
                topic: "btcpc/entries",
                data,
            }).await;
        }

        let mut cur = chain.current_epoch.write();
        if next_epoch > *cur { *cur = next_epoch; }
        last_produced = next_epoch;

        info!("miner: submitted Mine entry for epoch {}, tokens={}", next_epoch, work_value);
    }

    info!("miner: stopped");
}

async fn sleep_until_epoch(epoch: u64, genesis_ts: u64) {
    let start_ms = genesis_ts + epoch * EPOCH_MS;
    let now = now_ms();
    if start_ms > now {
        tokio::time::sleep(Duration::from_millis(start_ms - now)).await;
    }
}

fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as u64
}
