//! Inference mining loop for the Android micronode.
//!
//! work_value = tokens generated by the local candle LLM.
//! compute_proof = SHA-256 hex of the inference output.
//!
//! No SHA-256 grinding. Running the model IS the proof of work.

use std::sync::Arc;
use std::time::Duration;
use sha2::{Digest, Sha256};
use tracing::{info, warn};

use btcpc_types::{
    Block, BlockHeader, LedgerEntry, block_reward_at,
    era, RECYCLE_ERA, RECYCLE_FUND_ACCOUNT, RECYCLE_REWARD_RATE, RECYCLE_REWARD_DENOM,
    NATIVE_TOKEN, EPOCH_MS,
};

use crate::chain::Chain;
use crate::llm::LlmEngine;
use crate::net::NetCmd;

pub async fn run_miner(
    chain:       Arc<Chain>,
    account:     String,
    genesis_ts:  u64,
    llm:         Arc<tokio::sync::Mutex<LlmEngine>>,
    cmd_tx:      tokio::sync::mpsc::Sender<NetCmd>,
    mut shutdown: tokio::sync::broadcast::Receiver<()>,
) {
    info!("miner: started, account={}", account);

    let now = now_ms();
    if genesis_ts > now {
        let wait = genesis_ts - now;
        info!("miner: waiting {}s for genesis", wait / 1000);
        tokio::time::sleep(Duration::from_millis(wait)).await;
    }

    let mut last_produced = chain.store.latest_epoch().unwrap_or(0);

    loop {
        let next_epoch = last_produced + 1;

        tokio::select! {
            _ = shutdown.recv() => break,
            _ = sleep_until_epoch(next_epoch, genesis_ts) => {}
        }

        if chain.store.has_block(next_epoch) {
            last_produced = next_epoch;
            continue;
        }

        let prev_hash = chain.store.read_block(next_epoch.saturating_sub(1))
            .ok().flatten()
            .and_then(|b| Block::from_bytes(&b))
            .map(|b| b.header.hash())
            .unwrap_or([0u8; 32]);

        // Run on-device inference — this is the proof of work.
        let (work_value, compute_proof) = {
            let mut engine = llm.lock().await;
            if engine.ensure_ready().await {
                let prompt = format!(
                    "btcpc epoch {} miner {} prev {}",
                    next_epoch, account, &hex::encode(prev_hash)[..16]
                );
                match engine.generate(&prompt, 64).await {
                    Ok(output) => {
                        let tokens = output.split_whitespace().count() as u64;
                        let proof  = hex::encode(Sha256::digest(output.as_bytes()));
                        info!("miner: epoch {} — {} tokens", next_epoch, tokens);
                        (tokens, proof)
                    }
                    Err(e) => {
                        warn!("miner: inference failed epoch {}: {}", next_epoch, e);
                        (0, String::new())
                    }
                }
            } else {
                // Model still downloading — produce block with zero work this epoch.
                (0, String::new())
            }
        };

        match produce_block(&chain, &account, next_epoch, work_value, &compute_proof) {
            Ok(block) => {
                // Broadcast to peers.
                let mut data = next_epoch.to_be_bytes().to_vec();
                data.extend_from_slice(&block.to_bytes());
                let _ = cmd_tx.send(NetCmd::Broadcast {
                    topic: "btcpc/blocks",
                    data,
                }).await;

                let mut cur = chain.current_epoch.write();
                if next_epoch > *cur { *cur = next_epoch; }
                last_produced = next_epoch;
            }
            Err(e) => warn!("miner: block {} failed: {}", next_epoch, e),
        }
    }

    info!("miner: stopped");
}

// ── Block production ──────────────────────────────────────────────────────────

fn produce_block(
    chain:         &Chain,
    miner:         &str,
    epoch:         u64,
    work_value:    u64,
    compute_proof: &str,
) -> anyhow::Result<Block> {
    let prev_hash = chain.store.read_block(epoch.saturating_sub(1))?
        .and_then(|b| Block::from_bytes(&b))
        .map(|b| b.header.hash())
        .unwrap_or([0u8; 32]);

    let miner_id: [u8; 32] = Sha256::digest(miner.as_bytes()).into();

    let reward = if era(epoch) >= RECYCLE_ERA {
        let fund = chain.store.get_balance(RECYCLE_FUND_ACCOUNT, NATIVE_TOKEN);
        ((fund as u128 * RECYCLE_REWARD_RATE) / RECYCLE_REWARD_DENOM) as u64
    } else {
        block_reward_at(epoch)
    };

    let entries = vec![
        LedgerEntry::Mine {
            miner:      miner.to_owned(),
            epoch,
            work_value,
            block_hash: String::new(),
        },
        LedgerEntry::MineReward {
            miner:  miner.to_owned(),
            amount: reward,
            epoch,
        },
    ];

    chain.apply_block_entries(&entries);

    let entry_hashes: Vec<String> = entries.iter().map(|e| e.hash()).collect();
    let tx_root = btcpc_types::merkle_root(&entry_hashes);

    let mut header = BlockHeader::new(epoch as u32, prev_hash, miner_id);
    header.merkle_root_transactions = tx_root;

    let payload = serde_json::json!({
        "ledger_entries": entries,
        "compute_proofs": [{
            "worker":      miner,
            "output_hash": compute_proof,
            "tokens":      work_value,
            "epoch":       epoch,
        }],
        "chain_id": chain.chain_id,
    });

    let block = Block { header, payload };
    chain.store.write_block(epoch, &block.to_bytes())?;

    info!("miner: block {} — reward={} dreams, tokens={}", epoch, reward, work_value);
    Ok(block)
}

async fn sleep_until_epoch(epoch: u64, genesis_ts: u64) {
    let start_ms = genesis_ts + epoch * EPOCH_MS;
    let now = now_ms();
    if start_ms > now {
        tokio::time::sleep(Duration::from_millis(start_ms - now)).await;
    }
}

fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as u64
}
