//! Inference mining loop for the Android micronode.
//!
//! work_value = tokens generated by the local candle LLM.
//! compute_proof = SHA-256 hex of the inference output.
//!
//! No SHA-256 grinding. Running the model IS the proof of work.
//! Miners submit only a Mine entry; MineReward is emitted by clock nodes
//! after epoch seal quorum is reached.

use std::sync::Arc;
use std::time::Duration;
use sha2::{Digest, Sha256};
use tracing::{info, warn};

use hone_types::{LedgerEntry, EPOCH_MS};

use crate::chain::Chain;
use crate::llm::LlmEngine;
use crate::net::NetCmd;

pub async fn run_miner(
    chain:       Arc<Chain>,
    account:     String,
    genesis_ts:  u64,
    llm:         Arc<tokio::sync::Mutex<LlmEngine>>,
    cmd_tx:      tokio::sync::mpsc::Sender<NetCmd>,
    mut shutdown: tokio::sync::broadcast::Receiver<()>,
) {
    info!("miner: started, account={}", account);

    let now = now_ms();
    if genesis_ts > now {
        let wait = genesis_ts - now;
        info!("miner: waiting {}s for genesis", wait / 1000);
        tokio::time::sleep(Duration::from_millis(wait)).await;
    }

    let mut last_produced = chain.store.latest_epoch().unwrap_or(0);

    loop {
        let next_epoch = last_produced + 1;

        tokio::select! {
            _ = shutdown.recv() => break,
            _ = sleep_until_epoch(next_epoch, genesis_ts) => {}
        }

        // Run on-device inference — this is the proof of work.
        let model_id = std::env::var("HONE_MODEL")
            .unwrap_or_else(|_| "qwen2.5:0.5b".to_owned());
        let (input_tokens, output_tokens, output_hash) = {
            let mut engine = llm.lock().await;
            if engine.ensure_ready().await {
                let prompt = format!("hone epoch {} miner {}", next_epoch, account);
                match engine.generate(&prompt, 64).await {
                    Ok(output) => {
                        // candle doesn't expose input token count — approximate from whitespace
                        let in_toks  = prompt.split_whitespace().count() as u64;
                        let out_toks = output.split_whitespace().count() as u64;
                        let proof    = hex::encode(Sha256::digest(output.as_bytes()));
                        info!("miner: epoch {} — in={} out={} tokens", next_epoch, in_toks, out_toks);
                        (in_toks, out_toks, proof)
                    }
                    Err(e) => {
                        warn!("miner: inference failed epoch {}: {}", next_epoch, e);
                        (0, 0, String::new())
                    }
                }
            } else {
                (0, 0, String::new())
            }
        };

        // Build and apply Mine entry locally, then broadcast as gossip.
        let entry = LedgerEntry::Mine {
            miner:         account.clone(),
            epoch:         next_epoch,
            model:         model_id,
            input_tokens,
            output_tokens,
            tool_calls:    0,
            hw_tier:       0,
            output_hash:   output_hash.clone(),
            job_id:        None,
            node_version:  None,
            software_hash: None,
            model_hash:    None,
        };
        let _ = chain.apply_entry(&entry);

        let envelope = serde_json::json!({"entry": entry});
        if let Ok(data) = serde_json::to_vec(&envelope) {
            let _ = cmd_tx.send(NetCmd::Broadcast {
                topic: "hone/entries",
                data,
            }).await;
        }

        let mut cur = chain.current_epoch.write();
        if next_epoch > *cur { *cur = next_epoch; }
        last_produced = next_epoch;

        info!("miner: submitted Mine entry epoch {} out={} in={} tokens", next_epoch, output_tokens, input_tokens);
    }

    info!("miner: stopped");
}

async fn sleep_until_epoch(epoch: u64, genesis_ts: u64) {
    let start_ms = genesis_ts + epoch * EPOCH_MS;
    let now = now_ms();
    if start_ms > now {
        tokio::time::sleep(Duration::from_millis(start_ms - now)).await;
    }
}

fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as u64
}
