// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * wBTCPC — Wrapped Bitcoin Proof of Compute
 * Shin Devlin
 *
 * Cross-chain claim contract for BTCPC mining rewards on EVM chains.
 * Miners submit signed claim proofs generated by the BTCPC consensus layer.
 * Each epoch can only be claimed once per address. The signing authority
 * (consensus key) is rotatable by the contract owner for key rotation.
 */
contract wBTCPC is ERC20, Ownable {
    /// @notice 10 decimals — base10 to the tenth
    uint8 private constant _DECIMALS = 10;

    /// @notice The public address whose signatures authorize claim proofs
    address public signingAuthority;

    /// @notice Tracks which epochs have been claimed by each address
    mapping(address => mapping(uint256 => bool)) public epochClaimed;

    /// @notice Emitted when a miner claims wBTCPC for an epoch
    event Claimed(
        address indexed miner,
        uint256 indexed epoch,
        uint256 amount,
        uint256 period,
        uint256 crossChainRatio
    );

    /// @notice Emitted when the signing authority is rotated
    event SigningAuthorityUpdated(
        address indexed previousAuthority,
        address indexed newAuthority
    );

    /**
     * @param _signingAuthority Initial consensus signing key address
     */
    constructor(address _signingAuthority) ERC20("Wrapped BTCPC", "wBTCPC") Ownable(msg.sender) {
        require(_signingAuthority != address(0), "wBTCPC: zero address authority");
        signingAuthority = _signingAuthority;
    }

    /// @notice Override decimals to return 8 (matching native BTCPC)
    function decimals() public pure override returns (uint8) {
        return _DECIMALS;
    }

    /**
     * @notice Claim wBTCPC for a mined epoch.
     * @param epoch      The epoch number being claimed
     * @param amount     The raw token amount (8 decimal fixed-point, e.g. 24306000000 = 243.06 wBTCPC)
     * @param miner      The BTCPC miner identifier (bytes32-encoded account name)
     * @param proofSignature  ECDSA signature from the BTCPC consensus signing authority
     *
     * The proof message is: keccak256(abi.encodePacked(block.chainid, msg.sender, epoch, amount, miner))
     * This binds the proof to the specific chain, target wallet, epoch, amount, and miner.
     */
    function claim(
        uint256 epoch,
        uint256 amount,
        bytes32 miner,
        bytes memory proofSignature
    ) external {
        require(!epochClaimed[msg.sender][epoch], "wBTCPC: epoch already claimed");
        require(amount > 0, "wBTCPC: zero amount");

        // Reconstruct the message that was signed by the BTCPC consensus
        bytes32 messageHash = keccak256(
            abi.encodePacked(block.chainid, msg.sender, epoch, amount, miner)
        );

        // EIP-191 signed message hash
        bytes32 ethSignedHash = keccak256(
            abi.encodePacked("\x19Ethereum Signed Message:\n32", messageHash)
        );

        // Recover signer and verify against signing authority
        address recovered = _recoverSigner(ethSignedHash, proofSignature);
        require(recovered == signingAuthority, "wBTCPC: invalid proof signature");

        // Mark epoch as claimed for this address
        epochClaimed[msg.sender][epoch] = true;

        // Mint wBTCPC to the caller
        _mint(msg.sender, amount);

        emit Claimed(msg.sender, epoch, amount, 0, 0);
    }

    /**
     * @notice Update the signing authority (consensus key rotation).
     * @param newAuthority The new signing authority address
     */
    function updateSigningAuthority(address newAuthority) external onlyOwner {
        require(newAuthority != address(0), "wBTCPC: zero address authority");
        address previous = signingAuthority;
        signingAuthority = newAuthority;
        emit SigningAuthorityUpdated(previous, newAuthority);
    }

    /**
     * @notice Check if an epoch has been claimed by an address.
     * @param account The address to check
     * @param epoch   The epoch number
     * @return True if already claimed
     */
    function hasClaimed(address account, uint256 epoch) external view returns (bool) {
        return epochClaimed[account][epoch];
    }

    /**
     * @dev Recover the signer address from an ECDSA signature.
     */
    function _recoverSigner(bytes32 hash, bytes memory sig) internal pure returns (address) {
        require(sig.length == 65, "wBTCPC: invalid signature length");

        bytes32 r;
        bytes32 s;
        uint8 v;

        assembly {
            r := mload(add(sig, 32))
            s := mload(add(sig, 64))
            v := byte(0, mload(add(sig, 96)))
        }

        if (v < 27) {
            v += 27;
        }

        require(v == 27 || v == 28, "wBTCPC: invalid signature v value");

        return ecrecover(hash, v, r, s);
    }
}
