[package]
name = "hone-ft-example"
description = "BSP-20 fungible token example contract"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
hone-contract-sdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
borsh = { workspace = true }

# Minimize WASM binary size
[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
